import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { CreatePost } from '../components/post/CreatePost'
import { PostList } from '../components/post/PostList'
import { PostController } from '../components/post/PostController'
import { useEffect } from 'react'

export default function Home() {
  useEffect(() => {
    const interval = setInterval(() => {
      if (navigator.onLine) {
        window.location.reload(false);
      }
    }, 100000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>RIR-skjermer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div className='grid grid-rows-4 grid-cols-4 grid-flow-row gap-0 bg-black text-white'>
        <PostList />
        </div>
        <div className={styles.card}>
            <h2>Legg til ny post</h2>
            <CreatePost />
        </div>
        <div className={styles.card}>
            <h2>Kontroller innhold</h2>
            <PostController />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          En tjeneste av levert av {' '}
          <span className={styles.logo}>
            Reklameservice logo
          </span>
        </a>
      </footer>
    </div>
  )
}
