import Head from 'next/head'
import { CreatePost } from '../components/post/CreatePost'
import { PostList } from '../components/post/PostList'
import { PostController } from '../components/post/PostController'
import { useEffect } from 'react'

export default function Home() {
  useEffect(() => {
    const interval = setInterval(() => {
      if (navigator.onLine) {
        window.location.reload(false); 
      }
    }, 100000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div>
      <Head>
        <title>RIR-skjermer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div className='grid grid-rows-4 grid-cols-4 grid-flow-row gap-0 bg-black text-white'>
        <PostList />
        </div>
        <div>
            <h2>Legg til ny post</h2>
            <CreatePost />
        </div>
        <div>
            <h2>Kontroller innhold</h2>
            <PostController />
        </div>
      </main>

      <footer>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          En tjeneste av levert av {' '}
          <span>
            Reklameservice logo
          </span>
        </a>
      </footer>
    </div>
  )
}
